language: python
dist: precise #for pypy to work
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy" #commenting out pypy as does not work on trusty yet (travis new default)

#From https://docs.travis-ci.com/user/installing-dependencies/
#apt specific***
#before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/zesty/universe/binary-amd64/Packages"  -y
##  - echo "deb http://us.archive.ubuntu.com/ubuntu zesty main universe"  | sudo tee -a /etc/apt/sources.list
#  - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu universe"  -y
#  - sudo apt-get update -qq
#  - sudo apt-get install libstdc++6  libnlopt0 libnlopt-dev -y
#  - 

#Tr6 using addons  - and get key etc - if dont work install from source - *nkag
#prob do petsc here also apt or source rather than pip as pip is not favoured for non-pythin package by creater


matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          #- swig
	  libnlopt-dev


# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"

# command to run tests
#script: python setup.py test
script: ./test-script.sh

#add line to force commit
