language: python
python:
  - 2.7
  - 3.5
  
os: linux
dist: trusty
sudo: false

env:
  global:
    - HYDRA_LAUNCHER=fork
  matrix:
    - MPI=mpich
    - MPI=openmpi
    
cache: 
  pip: true
#  apt: true

# Setup Miniconda
before_install:
  # Do this conditionally because it saves some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # For debugging any issues with conda
  - conda create --yes --name condaenv python=$TRAVIS_PYTHON_VERSION 
  - source activate condaenv

# Currently mpi4py 2.0.0 fails with mpi_init error on some platforms - need dev version from source. 
# Means installing dependencies sep. - including MPI lib.
install:
  # Install on top of MPI library
  - if [[ "$MPI" == "mpich" ]]; then
      conda install -c conda-forge mpich;
    elif [[ "$MPI" == "openmpi" ]]; then
      conda install -c mpi4py openmpi;   
    fi
#  - pip install Cython #skip dodgy Cython version
#  - pip install git+https://bitbucket.org/mpi4py/mpi4py.git@master
#  - conda install cython
#  - conda install --yes mpi4py #Get MPI library
  - conda install --yes --no-update-deps mpi4py
  - python3 find_mpi.py
  - mpiexec --version
  - conda install --yes scipy
  - conda install --yes --no-update-deps -c conda-forge petsc4py #Will still conflict if using openMPI... no openmpi version???
  - conda install --yes -c conda-forge nlopt
  - conda install --yes pytest pytest-cov
  - conda install --yes -c conda-forge coveralls
#  - python setup.py install

# Run test
script:
  - code/tests/run-tests.sh

# Coverage
after_success:
  - mv code/tests/.cov* .
  - coveralls

after_failure:
  - cat code/tests/regression_tests/log.err
  
