language: python
python:
#  - 2.7
  - 3.6

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - conda create --yes --name condaenv python=$TRAVIS_PYTHON_VERSION 
  - source activate condaenv

# Currently mpi4py 2.0.0 fails with mpi_init error on some platforms - need dev version from source. 
# Means installing dependencies sep. - including MPI lib.
install:
#  - conda install --yes pip
  - conda install --yes cython
  - conda install --yes -c mpi4py openmpi  
  - conda install --yes mpi4py
#  - conda install --yes mpich2
  - pip install git+https://bitbucket.org/mpi4py/mpi4py.git@master
  - conda install --yes scipy 
  - conda install --yes pytest pytest-cov 
  - conda install --yes -c conda-forge petsc4py 
  - conda install --yes -c conda-forge nlopt 
#  - python setup.py install

# Run test
script:
  - ./run-tests.sh
 
