language: python
python:
  - 2.7
#  - 3.4
#  - 3.5
  - 3.6

# Attempt to speed up a bit
cache: 
   pip: true
   directories:
   - $HOME/miniconda

env:
  global:
   - MINICONDA_DIR="$HOME/miniconda"

# Setup anaconda
before_install:
  - sudo apt-get update
  # the miniconda directory may exist if it has been restored from cache 
  - if [ ! -d "$MINICONDA_DIR" ] || [ ! -e "$MINICONDA_DIR/bin/conda" ]; then
  -   rm -rf "$MINICONDA_DIR" # remove the directory in case we have an empty cached directory
  -   if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  -     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  -   else
  -     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  -   fi
  -   bash miniconda.sh -b -p $MINICONDA_DIR
  -   export PATH="$MINICONDA_DIR/bin:$PATH"
  -   hash -r
  -   conda config --set always_yes yes --set changeps1 no
  -   conda update -q conda
  -   conda info -a #for debugging conda
  - fi;
  - conda create --yes --name condaenv python=$TRAVIS_PYTHON_VERSION 
  - source activate condaenv

# Currently mpi4py 2.0.0 fails with mpi_init error on some platforms - need dev version from source. 
# Means installing dependencies sep. - including MPI lib.
install:
  - conda install --yes mpi4py
  - conda install --yes -c conda-forge petsc4py
  - conda install --yes -c conda-forge nlopt
  - conda install --yes pytest pytest-cov
  - conda install --yes -c conda-forge coveralls
  - conda install --yes scipy 
  - conda install --yes cython
  - pip install git+https://bitbucket.org/mpi4py/mpi4py.git@master
#  - python setup.py install #Need to test installation!!

# Run test
script:
#  - cd code/tests
#  - ./run-tests.sh
  - pwd
  - code/tests/run-tests.sh

# Coverage
after_success:
  - mv code/tests/.cov* .
  - coveralls
  #coveralls -d code/tests/.cov_merge_out

